### PR TITLE
Adds dedicated thread for processing non-rendering related tasks in DefaultRenderHost

### PR DESCRIPTION
**Pull request by holance**
Adds dedicated thread for processing non-rendering related tasks in DefaultRenderHost.

### CODE REVIEW

**Comment by kthyholdt** [comment]
are the daily builds down? I cant find this, nor anything from this year.

**Comment by holance** [comment]
You can download from https://ci.appveyor.com/project/holance/helix-toolkit-qqf1e/builds/46138701/artifacts

**Comment by kthyholdt** [comment]
can I add that package source to visual studio somehow?

**Comment by holance** [comment]
You can add a local folder as source.

**Pull request merged**
