### PR TITLE
Request for comments, Update HelixToolkit.WPF.SharpDX to SharpDx 3.0.2

### PR DESCRIPTION
**Pull request by SiNeumann**
This is a request for comments since I don't know if there is any plan to actually do this and it is not mergeable
I upgraded all SharpDx packeges to the latest version, which had some breaking changes. So in further steps we could make use Directx12 in the future.
Anyway the dll structure changed a bit eg. Color4,Rectangle and other structures are now within SharpDX.Mathematics.dll but still in SharpDx Namespace.

Loading of Textures changed since LoadFile and LoadMemory came from SharpDx Toolkit which itself isn't compatible with SharpDx 3.0.2. So TextureLoader (seen on Stackoverflow), should take care of this.
Currently dds files like in EnviromentMapExample are not working, I couldn't load them via SharpDX.WIC methods nor with System.Windows.Media.Imaging Methods, maybe someone has an idea.

All Demos were no .dds file is used are working.

### CODE REVIEW

**Comment by objorke** [comment]
Very cool! I hope we can get the textures loading again! 
I tried building your branch - but had to update the SharpDX.Direct2D1 package reference.
I also get a build error on the FileLoadDemo: PropertyChanged expected to be executed. You may also need to manually add '<PropertyChanged />' into your FodyWeavers.xml. eg <Weavers><PropertyChanged/></Weavers>. See https://github.com/Fody/Fody/wiki/SampleUsage

**Comment by objorke** [comment]
I have also fixed the build. There should be updated packages on myget

**Comment by SteveLockley** [comment]
I have tried to build and execute this on a windows 10 platform and it fails to create the device.

The machine also has the latest 2010 DirectX SDK on, the error is always caused by new Direct3DEx()
Here is the trace
SharpDX.SharpDXException: HRESULT: [0x8876086C], Module: [SharpDX.Direct3D9], ApiCode: [D3DERR_INVALIDCALL/InvalidCall], Message: Unknown
   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D9.Direct3DEx.CreateDeviceEx(Int32 adapter, DeviceType deviceType, IntPtr hFocusWindow, Int32 behaviorFlags, PresentParameters[] presentationParametersRef, DisplayModeEx[] fullscreenDisplayModeRef, DeviceEx returnedDeviceInterfaceOut)
   at SharpDX.Direct3D9.DeviceEx..ctor(Direct3DEx direct3D, Int32 adapter, DeviceType deviceType, IntPtr controlHandle, CreateFlags createFlags, PresentParameters presentParameters)
   at HelixToolkit.Wpf.SharpDX.DX11ImageSource.StartD3D() in C:\Users\Steve\Source\Repos\helix-toolkit\Source\HelixToolkit.Wpf.SharpDX\Controls\DX11ImageSource.cs:line 135
   at HelixToolkit.Wpf.SharpDX.DX11ImageSource..ctor(Int32 adapterIndex) in C:\Users\Steve\Source\Repos\helix-toolkit\Source\HelixToolkit.Wpf.SharpDX\Controls\DX11ImageSource.cs:line 53
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.StartD3D() in C:\Users\Steve\Source\Repos\helix-toolkit\Source\HelixToolkit.Wpf.SharpDX\Controls\DPFCanvas.cs:line 280
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.EffectsManagerPropertyChanged() in C:\Users\Steve\Source\Repos\helix-toolkit\Source\HelixToolkit.Wpf.SharpDX\Controls\DPFCanvas.cs:line 732
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.<>c.<.cctor>b__58_0(DependencyObject s, DependencyPropertyChangedEventArgs e) in C:\Users\Steve\Source\Repos\helix-toolkit\Source\HelixToolkit.Wpf.SharpDX\Controls\DPFCanvas.cs:line 143
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.set_EffectsManager(IEffectsManager value) in C:\Users\Steve\Source\Repos\helix-toolkit\Source\HelixToolkit.Wpf.SharpDX\Controls\DPFCanvas.cs:line 148
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.StartD3D() in C:\Users\Steve\Source\Repos\helix-toolkit\Source\HelixToolkit.Wpf.SharpDX\Controls\DPFCanvas.cs:line 276
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.OnLoaded(Object sender, RoutedEventArgs e) in C:\Users\Steve\Source\Repos\helix-toolkit\Source

**Comment by SteveLockley** [comment]
I think this is caused by the Warp driver, if I force the adapter to choose the hardware option then it works fibe, entering the code that support WARP in Helix causes the problem above

**Comment by SteveLockley** [comment]
I am quite new to device drivers but have managed to fix this for my machine, it needs to be tested on others. The problem is cause in the GetBestAdapter function for me. The Microsoft Basic renderer is chosen in preference to my hardware device. I have added a clause to stop this

if (item.Description.VendorId == 0x1414 || item.Description.DeviceId == 0x8c)
                    {
                        continue;
                    }
Any advice would be welcome please

**Comment by holance** [comment]
Close this pull. Has been upgraded to SharpDX 3.1.1 #390

**Pull request closed without merging**
