### PR TITLE
Bugfix in GridLinesVisual3D

### PR DESCRIPTION
**Pull request by chrkon**
Issue #136 (Bug in GridLinesVisual 3D) fixed

### CODE REVIEW

**Comment by objorke** [comment]
Do we have a demo covering the `GridLinesVisual3D`?

**Comment by chrkon** [comment]
Yes and No ... 
In the Example for CursorPosition (#133, PR #138) you can set the construction plane manually by editing the normal vector. In that example there are two GridLinesVisual3D elements. A blue one which represents the XY plane and a red one, which can be changed manually.
Is this OK?

**Comment by objorke** [comment]
OK, I will test in the cursor position demo

**Comment by chrkon** [comment]
Build failed after merging? I have just changed one source code file for this bugfix. I don't think that my changes are relevant for this buil failure. 
But how can I help?

**Comment by objorke** [comment]
I think it was an AppVeyor timeout.

**Comment by chrkon** [comment]
Yes it seems that a DDoS attack on GitHub is active. See: https://status.github.com/messages

**Pull request merged**
