### PR TITLE
Advanced ViewCube and speedUP of HitTesting in GeometryModel3D

### PR DESCRIPTION
**Pull request by jotschgl**
Added the ability to click on every corner and every Edge on the ViewCube (#1) 

Speed up Hittesting ing the Geometrymodel3D by not using the whole geometry but only the Bounds

### CODE REVIEW

**Comment by objorke** [comment]
I agree it would be nice to have a dependency property that enables the edge click feature!

**Comment by jotschgl** [comment]
The text on each side is the same as before. I just added the edges and corners.
But I also think that it would be nice to have the option to dis-/enable the feature.

**Comment by holance** [comment]
Seems like there is a build error due to lack of Summary for DependencyProperties?

**Comment by objorke** [comment]
yes, missing comment on HelixViewport3D.IsViewCubeEdgeClicksEnabled

**Comment by holance** [comment]
Hi Oystein,

The comments have been fixed. #320 is ready to merge.

Best,
Lunci

**Pull request merged**
