### PR TITLE
"Zoom extents" doesn't work correctly for BillboardText

### PR DESCRIPTION
**Pull request by ZHZG**
Add an interface that the bounds of the visual will be ignored.
Solves #229

### CODE REVIEW

**Comment by objorke** [comment]
It looks good now! Thanks for cleaning up!
Now only two items left:
1. update the change log and contributors file
2. squash the commits (rebase interactively, edit commit message, push -f) Note that you don't need to create a new PR - it is OK to rewrite the commit history here

For the change log, I suggest to add under the "Added" section:
"Ignore visuals that implement IBoundsIgnoredVisual3D in the bounds calculation (#229)"

**Comment by ZHZG** [comment]
I have updated the log, but have difficulty to rebase.

**Comment by objorke** [comment]
OK, good! I will accept this!
Please use rebase in the next PR! :-)

**Comment by ZHZG** [comment]
Hi Øystein,

I have one question about HelixToolkit.

I get the latest HelixToolkit built and find it is based on .Net 4.5 while our Brix project is on .Net4.0.

Much appreciated if you could give some ideas on this.

Thanks,

Zonggui

**Comment by objorke** [comment]
The NuGet package contains both .NET 4.0 and .NET 4.5 binaries (in the lib/NET40 and lib/NET45 folders). NuGet should automatically pick the right one.
The build artifacts contains both NET40 and NET45 binaries.
You can find the latest at
https://ci.appveyor.com/project/objorke/helix-toolkit/build/2015.1.651/artifacts

**Pull request merged**
