### PR TITLE
Improve converter performance

### PR DESCRIPTION
**Pull request by JeremyAnsel**
Simplify the vector conversions

### CODE REVIEW

**Comment by JeremyAnsel** [comment]
I did a few benchmarks.

In V2 (2.24.0), I used this code:
```cs
    [Benchmark]
    public System.Windows.Media.Media3D.MeshGeometry3D MeshBuilderTest1_V2()
    {
        var mb = new HelixToolkit.Wpf.MeshBuilder();

        for (int i = 0; i < 10; i++)
        {
            mb.AddSphere(new(), 1, 256, 256);
        }

        var mesh = mb.ToMesh();
        return mesh;
    }
```

In V3 (3.0.0-develop3-0001), I used this code:
```cs
    [Benchmark]
    public System.Windows.Media.Media3D.MeshGeometry3D MeshBuilderTest1_V3()
    {
        var mb = new HelixToolkit.MeshBuilder();

        for (int i = 0; i < 10; i++)
        {
            mb.AddSphere(new(), 1, 256, 256);
        }

        var mesh = mb.ToMesh().ToMeshGeometry3D();
        return mesh;
    }
```

The results for V2 are:
| Method              | Mean     | Error | Allocated |
|-------------------- |---------:|------:|----------:|
| MeshBuilderTest1_V2 | 243.5 ms |    NA | 356.14 MB |

The results for V3 are:
| Method              | Mean     | Error | Allocated |
|-------------------- |---------:|------:|----------:|
| MeshBuilderTest1_V3 | 180.5 ms |    NA | 330.17 MB |

The results for V3 with this PR are:
| Method              | Mean     | Error | Allocated |
|-------------------- |---------:|------:|----------:|
| MeshBuilderTest1_V3 | 127.6 ms |    NA | 151.28 MB |

**Comment by JeremyAnsel** [comment]
In SharpDX,
With these benchmarks:
```cs
    [Benchmark]
    public HelixToolkit.SharpDX.MeshGeometry3D MeshBuilderTest1_V3_v1()
    {
        var mb = new HelixToolkit.MeshBuilder();

        for (int i = 0; i < 10; i++)
        {
            mb.AddSphere(new(), 1, 256, 256);
        }

        var mesh = mb.ToMesh().ToMeshGeometry3D();
        return mesh;
    }

    [Benchmark]
    public HelixToolkit.SharpDX.MeshGeometry3D MeshBuilderTest1_V3_v2()
    {
        var mb = new HelixToolkit.MeshBuilder();

        for (int i = 0; i < 10; i++)
        {
            mb.AddSphere(new(), 1, 256, 256);
        }

        var mesh = mb.ToMeshGeometry3D();
        return mesh;
    }
```
The results are:
| Method                 | Mean      | Error | Allocated |
|----------------------- |----------:|------:|----------:|
| MeshBuilderTest1_V3_v1 |  88.27 ms |    NA |  96.02 MB |
| MeshBuilderTest1_V3_v2 | 102.19 ms |    NA | 196.11 MB |

**Comment by holance** [comment]
In Sharpdx test, v1 is faster than v2?

**Comment by JeremyAnsel** [comment]
Yes, v1 is faster than v2.

**Comment by JeremyAnsel** [comment]
With
```cs
    [Benchmark]
    public HelixToolkit.SharpDX.MeshGeometry3D SharpDX_ToMesh_AddSphere_v1()
    {
        var mb = new HelixToolkit.MeshBuilder();

        mb.AddSphere(new(), 1, 256, 256);

        var mesh = mb.ToMesh().ToMeshGeometry3D();
        return mesh;
    }

    [Benchmark]
    public HelixToolkit.SharpDX.MeshGeometry3D SharpDX_ToMesh_AddSphere_v2()
    {
        var mb = new HelixToolkit.MeshBuilder();

        mb.AddSphere(new(), 1, 256, 256);

        var mesh = mb.ToMesh().ToMeshGeometry3D();
        return mesh;
    }

    [Benchmark]
    public HelixToolkit.SharpDX.MeshGeometry3D SharpDX_ToMesh_AddSphere_10_v1()
    {
        var mb = new HelixToolkit.MeshBuilder();

        for (int i = 0; i < 10; i++)
        {
            mb.AddSphere(new(), 1, 256, 256);
        }

        var mesh = mb.ToMesh().ToMeshGeometry3D();
        return mesh;
    }

    [Benchmark]
    public HelixToolkit.SharpDX.MeshGeometry3D SharpDX_ToMesh_AddSphere_10_v2()
    {
        var mb = new HelixToolkit.MeshBuilder();

        for (int i = 0; i < 10; i++)
        {
            mb.AddSphere(new(), 1, 256, 256);
        }

        var mesh = mb.ToMeshGeometry3D();
        return mesh;
    }

    [Benchmark]
    public HelixToolkit.SharpDX.MeshGeometry3D SharpDX_ToMesh_AddCube_10000_v1()
    {
        var mb = new HelixToolkit.MeshBuilder();

        for (int i = 0; i < 10000; i++)
        {
            mb.AddCube();
        }

        var mesh = mb.ToMesh().ToMeshGeometry3D();
        return mesh;
    }

    [Benchmark]
    public HelixToolkit.SharpDX.MeshGeometry3D SharpDX_ToMesh_AddCube_10000_v2()
    {
        var mb = new HelixToolkit.MeshBuilder();

        for (int i = 0; i < 10000; i++)
        {
            mb.AddCube();
        }

        var mesh = mb.ToMeshGeometry3D();
        return mesh;
    }
```
the results are:
| Method                          | Mean      | Error | Allocated |
|-------------------------------- |----------:|------:|----------:|
| SharpDX_ToMesh_AddSphere_v1     |  8.203 ms |    NA |  12.01 MB |
| SharpDX_ToMesh_AddSphere_v2     |  8.395 ms |    NA |  12.01 MB |
| SharpDX_ToMesh_AddSphere_10_v1  | 82.003 ms |    NA |  96.01 MB |
| SharpDX_ToMesh_AddSphere_10_v2  | 96.261 ms |    NA | 196.09 MB |
| SharpDX_ToMesh_AddCube_10000_v1 | 14.980 ms |    NA |  34.24 MB |
| SharpDX_ToMesh_AddCube_10000_v2 | 18.000 ms |    NA |  54.38 MB |

**Comment by JeremyAnsel** [comment]
With
```cs
    private HelixToolkit.MeshBuilder _sphere;

    [GlobalSetup]
    public void GlobalSetup()
    {
        _sphere = new HelixToolkit.MeshBuilder();

        for (int i = 0; i < 100; i++)
        {
            _sphere.AddSphere(new(), 1, 256, 256);
        }
    }

    [Benchmark]
    public HelixToolkit.SharpDX.MeshGeometry3D SharpDX_ToMesh_v1()
    {
        var mesh = _sphere.ToMesh().ToMeshGeometry3D();
        return mesh;
    }

    [Benchmark]
    public HelixToolkit.SharpDX.MeshGeometry3D SharpDX_ToMesh_v2()
    {
        var mesh = _sphere.ToMeshGeometry3D();
        return mesh;
    }
```
the results are
| Method            | Mean     | Error | Allocated    |
|------------------ |---------:|------:|-------------:|
| SharpDX_ToMesh_v1 | 174.3 ms |    NA |            - |
| SharpDX_ToMesh_v2 | 325.7 ms |    NA | 1049410032 B |

**Comment by JeremyAnsel** [comment]
When using `meshBuilder.ToMesh().ToMeshGeometry3D()`, the method `CollectionExtensions.ToMeshGeometry3D` is called.
This method doesn't make a copy of the mesh data.
```cs
    public static MeshGeometry3D ToMeshGeometry3D(this HelixToolkit.Geometry.MeshGeometry3D mesh)
    {
        return new MeshGeometry3D
        {
            Positions = mesh.Positions,
            Normals = mesh.Normals,
            TextureCoordinates = mesh.TextureCoordinates,
            Tangents = mesh.Tangents,
            BiTangents = mesh.BiTangents
        };
    }
```

When using `meshBuilder.ToMeshGeometry3D()`, the method `Converter.ToMeshGeometry3D` is called.
This method makes a copy of the mesh data.
```cs
    public static MeshGeometry3D ToMeshGeometry3D(this MeshBuilder builder)
    {
        return new MeshGeometry3D
        {
            Normals = ((builder.Normals != null) ? new Vector3Collection(builder.Normals) : null),
            Positions = ((builder.Positions != null) ? new Vector3Collection(builder.Positions) : null),
            TextureCoordinates = ((builder.TextureCoordinates != null) ? new Vector2Collection(builder.TextureCoordinates) : null),
            TriangleIndices = ((builder.TriangleIndices != null) ? new IntCollection(builder.TriangleIndices) : null),
            Tangents = ((builder.Tangents != null) ? new Vector3Collection(builder.Tangents) : null),
            BiTangents = ((builder.BiTangents != null) ? new Vector3Collection(builder.BiTangents) : null)
        };
    }
```

**Comment by JeremyAnsel** [comment]
In the `HelixToolkit.SharpDX.Converter` class there is this method: 
`public static MeshGeometry3D ToMeshGeometry3D(this MeshGeometry3D mesh)`
Is it fine or should it be
`public static MeshGeometry3D ToMeshGeometry3D(this HelixToolkit.Geometry.MeshGeometry3D mesh)` ?

**Comment by holance** [comment]
I will fix these inconsistencies.

**Pull request merged**
