### PR TITLE
Ability to add caps in HelixToolkit.SharpDx meshbuilder. Fix caps normal issue in TubeVisual in WPF version

### PR DESCRIPTION
**Pull request by holance**
Added ability to add caps in HelixToolkit.SharpDx meshbuilder. 

Fix caps normal issue in TubeVisual in WPF version

### CODE REVIEW

**Comment by Iluvatar82** [comment]
As mentioned in issue #332, this was already solved in pull request #335! I solved it not in the mesh builder but in the file "HelixToolkit.Wpf/Visual3Ds/MeshVisuals/TubeVisual3D.cs" because it's a property of this class only. This pr is redundant.

**Comment by holance** [comment]
I know, but your solution did not specify the cap vertex normal properly,
causes lightening issue. I also added the cap in sharpdx version.

**Comment by Iluvatar82** [comment]
Ok then, I just thought a solution in Wpf was needed, and since no equivalent to the TubeVisual3D exists in SharpDX I decided to implement it in the Tube's Tesselate function (as you mentioned in the issue #332 I think).

**Comment by holance** [comment]
Yes, maybe my check in notes are a little bit confusing.  I added the cap function in sharpdx meshbuilder. And corrected the vertex normal issue in WPF TubeVisual tesselation. :)

**Pull request merged**
