### PR TITLE
#133 new Cursor Property in HelixViewport3D

### PR DESCRIPTION
**Pull request by chrkon**
New CursorPosition properties are added to the HelixViewport3D.

A `ConstructionPlane` Property is added, too. It holds a simple Plane3D object. This plane is independent from the View, and can be set freely. Per default it is set to 0;0;1 (XY plane).

With these Properties we can now get the following Positions:
* `CursorPosition` ; the 3D Position based on the Camera View 
* `CursorOnElementPosition`; the 3D coordinate on a hit Element. If no Element is hit, this Position is `null`
* `CursorOnConstructionPlane` ; the 3D coordinate on the Construction plane.

### CODE REVIEW

**Comment by chrkon** [comment]
Sorry, I was not able to remove the GIT commits with the german text. :-(

**Comment by objorke** [comment]
Looks very good!
1. please do not use [#region](http://programmers.stackexchange.com/questions/53086/are-regions-an-antipattern-or-code-smell)
2. can you please make a new branch on your fork, and squash all the commits into one? this will make the commit history on the master much cleaner

**Comment by objorke** [comment]
What about pulling the latest from HelixToolkit upstream/master, creating a new branch on your fork (e.g. "features/cursor-position") then soft reset (keeping all changes), and create one commit including #133 in the description, create a new PR for the new branch (include #133 in the PR description, not the title)

Sorry for the nitpicking here...

I tried it locally in SourceTree on your fork:
image
But I would like you to do this to get the right Author name! :-)

**Comment by chrkon** [comment]
I try again :-)

**Pull request closed without merging**
