### PR TITLE
Use $version$ in nuspec files

### LINKED ISSUE #125: Nuget install does not work
Hi,

I've tried to install Sharp HelixToolkit.Wpf.SharpDX via nuget and does not work.  For some reason it installs version 2015.1.474 of SharpDX which expects the same version of HelixToolkit.Wpf.  What is installed is 2014.2.414.0 of Wpf.  I've tried uninstalling and installing manually via the package manager console but get the same problem.  When I install HT.Wpf it says "Installing 'HelixToolkit.Wpf 2015.1.474' but I still get version 2014.2.414.0.

I may be doing something wrong, but I can't work out what.

Tim

### PR DESCRIPTION
**Pull request by JeremyAnsel**
Fix #125

### CODE REVIEW

**Comment by JeremyAnsel** [comment]
`UpdateVersionNumbers` will replace `$version$` with the version specified in the command line.

**Comment by objorke** [comment]
Need to resolve conflicts before merging. @JeremyAnsel can you do this on your fork?

**Comment by JeremyAnsel** [comment]
Done.

**Comment by objorke** [comment]
Thanks!

**Comment by objorke** [comment]
Sorry, this must be fixed - build is failing - the string to be replaced should be "$version"!
https://github.com/objorke/lynx-toolkit/blob/master/Source/UpdateVersionNumbers/Program.cs#L291

**Pull request merged**
