### PR TITLE
Update helix to sharp dx0.2.6.3

### PR DESCRIPTION
**Pull request by ikeough**
This PR does the following:

- Updates the SharpDX packages from 2.5.0 -> 2.6.3.
- Removes lines from the CanvasMock that were incompatible with the new version of SharpDX, but were not being used anywhere.
- Adds links to the obj model test files in the .net 4.0 project so that the model files are correctly copied to the output directory and the tests pass when compiling that solution. These links already existed in the .net 4.5 project.
- Updates the `AppVeyor.yml` file to call nuget restore `before_build`, as suggested [here](http://help.appveyor.com/discussions/problems/1239-how-to-get-more-logs-for-exception-has-been-thrown-by-the-target-of-an-invocation-errors#comment_35592708).

FYI @objorke

### CODE REVIEW

**Comment by objorke** [comment]
I would like to merge this enhancement, but the build is broken.. Can you see what is wrong?

**Comment by ikeough** [comment]
Doing a little research on this problem:
http://help.appveyor.com/discussions/problems/1239-how-to-get-more-logs-for-exception-has-been-thrown-by-the-target-of-an-invocation-errors#comment_35592708

**Comment by ikeough** [comment]
@objorke Finally figured this out. When the SharpDX 2.6.3 nuget is installed, it runs a script that edits the project files to include an environment variable `SharpDXBinDir`. This was not evaluating correctly on AppVeyor, because the directory that it would point at had not yet been created. By editing the `AppVeyor.yml` to call nuget restore before build, it takes care of this.

**Comment by objorke** [comment]
Great! Looking forward to merge this 3month old PR! Should (some of) the commits be squashed?

**Comment by ikeough** [comment]
@objorke squashed :)

**Comment by objorke** [comment]
thanks!

**Pull request merged**
