### PR TITLE
Potential fix for sluggish during mouse rotation every few seconds(#327)

### PR DESCRIPTION
**Pull request by holance**
#327

Potential fix for sluggish during mouse rotation every few seconds.

I think the underlying issue for the sluggish is because the rendering is done by Rendering thread(CompositeTarget), but in some cases, the code also use Dispatcher to do rendering by using UI thread. Seems like there is a performance impact if keep switching between these two renderings. I just removed the dispatcher rendering part and only uses rendering thread. 

Need help to do some test or a code review. Please let me know the results.

### CODE REVIEW

**Comment by BetaRavener** [comment]
I can try this patch on my scene that was being sluggish later today or tomorrow. The code looks ok at first glance, although I'm not sure it there is problem only with mouse camera rotation. If there are more code paths affected by this, maybe the discarding of event shouldn't be done like it is now in `MouseGestureHandler.cs` but in renderer. However, it should be sufficient for testing if the problem was resolved by this.

**Comment by holance** [comment]
Make sure to include my latest checkin, seems like it fixes the FPS overshoot(now keeps at 120 fps max) during mouse rotation.

**Comment by BetaRavener** [comment]
I built the latest version of your fork. Doesn't look like it solves my problem. I'll try to make screen capture tomorrow to illustrate what I'm experiencing.

**Comment by holance** [comment]
It solved my problem very well. What's the number for
'lastRenderingDuration' on your side? There are still some performance
issue if it runs on my 3 years old laptop. But runs well on my desktop. I
think there are still some spaces to tweak to improve the performance.

**Comment by holance** [comment]
@BetaRavener These are some things I noticed during the performance investigation.
1. When I run the example on my 3 year old laptop, debug mode is actually more smooth than release mode during mouse rotation. I think the root cause is mouse move event fires too frequent, it may cause the rendering thread to busy to keep up. I limit the mouse event frequency in latest commit. Please try it and see if you have any performance gain for your test case.
2. MSAA is always set to the maximum the graphic card can support, but not the graphic card can handle for actual rendering. So I put the dependency property so user can manually set MSAA level. You can try to disable MSAA completely. 

Please let me know if any of these helps your issue.

**Comment by BetaRavener** [comment]
Sorry I'm bit bussy these days, will try out in the next 2 days :) Thanks for all the work.

**Pull request merged**
