### PR TITLE
Auto recover from monitor configuration change

### PR DESCRIPTION
**Pull request by holance**
Check device state when front buffer changed. 
Recover from exception during setting back buffer.
#1531

### CODE REVIEW

**Comment by kthyholdt** [comment]
Thanks a lot for this @holance great work! Is it possible to make a new release soon so we can get this into our software?

**Comment by holance** [comment]
@kthyholdt Could you use the nightly build? Or have to be released version?

**Comment by kthyholdt** [comment]
I could, but if you plan to make a new release in a couple of weeks I'd rather wait for that.

**Comment by holance** [comment]
I am not planning to make an new release yet.

**Pull request merged**
