### PR TITLE
When RotateAroundMouseDownPoint and ZoomAroundMouseDownPoint are both…

### PR DESCRIPTION
**Pull request by ChaosSorcerer**
When RotateAroundMouseDownPoint and ZoomAroundMouseDownPoint are both on the camera target position may get really close/very far from the camera, causing bad/unexpected camera interaction when not hovering over an object. See https://github.com/helix-toolkit/helix-toolkit/issues/1028 for more information.

Added a Closest3DPointHitTester and used it to allow rotating around the closest vertex instead of always using the unprojected position when no meshes are under the mouse curser.

### CODE REVIEW

**Comment by holance** [comment]
If finding closest vertex is too costly, maybe just find the closest Model3D Bound or the center of the Bound?

**Comment by ChaosSorcerer** [comment]
Added the option to use the closest model3D bound on large meshes.

**Comment by ChaosSorcerer** [comment]
Also made a small addition to avoid zooming and rotating around vertices that are not currently visible within the view

**Comment by hansmei** [comment]
How about adding this code for the WPF.SharpDX CameraController as well?

**Comment by holance** [comment]
Usually I would suggest to use FixedRotationPoint and do your own HitTest and find the Point you want to rotate. Using RotateAroundMouseDownPoint/ZoomAroundMouseDownPoint are not really a reliable way to control this kind of behavior since you may use mouse down on viewport for many other different behaviors.

**Comment by hansmei** [comment]
Many applications are using the zoom event to set a pivot point (preferably with a ball marker) on hit for which the rotation would rotate around.

That is the kind of behaviour I'm missing so far with the current abilities of the WPF.SharpDX project. I have tried to tweak many different settings, but setting a pivot (fixed rotation point) does not seem to work the way I want to. An ability to set a pivot point on zoom for the rotation would be great.

**Pull request merged**
